// This file is auto-generated by scripts/gen-commands-index.js.
// Do not edit manually.
import createEvent from "./create-event";
import listEvents from "./list-events";

export const commands = [createEvent, listEvents];
